apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-1-a
  namespace: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-1-a
  template:
    metadata:
      labels:
        app: web-app-1-a
    spec:
      containers:
      - name: nginx
        image: nginx:1.28.0
        ports:
        - containerPort: 80
