apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-2-a
  namespace: app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-2-a
  template:
    metadata:
      labels:
        app: web-app-2-a
    spec:
      containers:
      - name: nginx
        image: nginx:1.26.2
        ports:
        - containerPort: 80
